title: Decision Labs - Blog
description: 'https://decision-labs.com'
social_link: twitter
social_username: decision-labs
github_repo: decision-labs
github_username: decision-labs
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /blog_decision_labs
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
